pipeline:
  test:
    image: node:${NODE_VERSION}
    environment:
      - NODE_ENV=test
    commands:
      - node -v
      - yarn -v
      - uname -r
      - yarn install --ignore-engines
      - yarn add v8-profiler-node8 --ignore-engines
      - yarn add gc-stats --ignore-engines
      - export PATH=$PATH:./node_modules/.bin/
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - runTest () { if [ "$NODE_VERSION" = "11" ]; then nyc --clean false --require ts-node/register --require source-map-support/register mocha $*; else mocha --require ts-node/register $*; fi ;}
      - runTest mocha test/api.spec.ts
      - runTest mocha test/autoExit.spec.ts
      - runTest test/features/eventLoopInspector.spec.ts
      - runTest test/features/events.spec.ts
      - runTest test/features/profiling.spec.ts
      - runTest test/metrics/eventloop.spec.ts
      - runTest test/metrics/http.spec.ts
      - runTest test/metrics/network.spec.ts
      - runTest test/metrics/v8.spec.ts
      - runTest test/services/actions.spec.ts
      - runTest test/services/metrics.spec.ts
      - nyc report --reporter lcov || echo "No nyc coverage"
      - ./cc-test-reporter after-build --exit-code 0 || echo “Skipping CC coverage upload” or upload-coverage || echo “Skipping CC coverage upload”
    secrets: [ cc_test_reporter_id ]
    when:
      event: push
  slack:
    image: plugins/slack
    channel: ci
    status: [ success, failure ]
    template: |
      {{#success build.status}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" with node:${NODE_VERSION} done by {{build.author}} succeeded in {{since build.started}}
      {{else}}
        {{repo.name}} : {{build.event}} with commit {{truncate build.commit 8}} on branch "{{build.branch}}" with node:${NODE_VERSION} done by {{build.author}} failed in {{since build.started}}
      {{/success}}
      see {{ build.link }}
    secrets: [ slack_webhook ]
  build:
    image: node:${NODE_VERSION}
    commands:
      - node -v
      - yarn -v
      - uname -r
      - yarn 2> /dev/null
      - export PATH=$PATH:./node_modules/.bin/
      - mkdir build
      - yarn build
    when:
      event: [ tag ]
matrix:
  NODE_VERSION:
    - 4
    - 6
    - 8
    - 10
    - 11
